[project]
name = "pta-ciencia-de-dados-equipe-julia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agno>=2.3.2",
    "google-genai>=1.52.0",
    "python-dotenv>=1.2.1",
    "tavily-python>=0.7.13",
]
